#!/bin/sh
echo ">> RUNNING pre-commit GITHOOK in .githooks/"
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g' | grep -o 'frontend.*' | sed 's/frontend\///g')
[ -z "$FILES" ] && exit 0

# Run prettier on all selected files
cd frontend
echo ">> RUNNING PRETTIER"
echo "$FILES" | xargs npx prettier --write --ignore-path .gitignore
echo ">> FINISHED PRETTIER"
echo ">> RUNNING ESLINT"
echo "$FILES" | xargs npx eslint --max-warnings 0 --ext .js,.ts,.jsx,.tsx --fix --ignore-path .gitignore
echo ">> FINISHED ESLINT"

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0